[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
spacetimedb-sdk = "1.1"
hex = "0.4"

[dependencies.godot]
git = "https://github.com/godot-rust/gdext"
branch = "master"